# RDS resources
RDSSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription: Open database for access
    SecurityGroupIngress:
    - IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      CidrIp: 0.0.0.0/0

RDSInstance:
  Type: AWS::RDS::DBInstance
  Properties:
    DBInstanceIdentifier: ${self:custom.projectPrefix}-RDS
    DBInstanceClass: db.t2.micro
    Engine: postgres
    EngineVersion: 10.4
    PubliclyAccessible: false
    AllocatedStorage: 20
    MultiAZ: false
    DBName: ${self:provider.environment.RDS_DB_NAME}
    MasterUsername: ${self:provider.environment.RDS_DB_MASTER_USER}
    MasterUserPassword: ${self:provider.environment.RDS_DB_MASTER_PWD}
    VPCSecurityGroups:
    - Fn::GetAtt: [ RDSSecurityGroup, GroupId ]
  DependsOn: RDSSecurityGroup
  DeletionPolicy: Snapshot