# Cognito resources
UserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: ${self:custom.projectPrefix}-UserPool
    AdminCreateUserConfig:
      AllowAdminCreateUserOnly: true
      UnusedAccountValidityDays: 7
      InviteMessageTemplate: ${self:provider.environment.REGISTER_INVITATION}
    AutoVerifiedAttributes:
      - phone_number
      - email
    MfaConfiguration: OPTIONAL
    Policies:
      PasswordPolicy:
        MinimumLength: 8
        RequireLowercase: true
        RequireUppercase: true
        RequireNumbers: true
        RequireSymbols: true
    SmsConfiguration:
      ExternalId: ${self:custom.projectPrefix}-external
      SnsCallerArn:
        Fn::GetAtt: [SNSRole, Arn]
    Schema:
      - Name: name
        AttributeDataType: String
        Mutable: true
        Required: true
      - Name: family_name
        AttributeDataType: String
        Mutable: true
        Required: true
      - Name: birth_date
        AttributeDataType: DateTime
        Mutable: true
        Required: false
      - Name: ssn
        AttributeDataType: String
        Mutable: false
        Required: false
      - Name: email
        AttributeDataType: String
        Mutable: false
        Required: false
      - Name: phone_number
        AttributeDataType: String
        Mutable: false
        Required: true
    UsernameAttributes:
      - email
      - phone_number

UserPoolClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    ClientName: ${self:custom.projectPrefix}-UserPoolClient
    GenerateSecret: false
    UserPoolId:
      Ref: UserPool

# RDS resources
RDSSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription: Open database for access
    SecurityGroupIngress:
    - IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      CidrIp: 0.0.0.0/0

RDSInstance:
  Type: AWS::RDS::DBInstance
  Properties:
    DBInstanceIdentifier: ${self:custom.projectPrefix}-RDS
    DBInstanceClass: db.t2.micro
    Engine: postgres
    EngineVersion: 10.4
    PubliclyAccessible: false
    AllocatedStorage: 20
    MultiAZ: true
    DBName: ${self:provider.environment.RDS_DB_NAME}
    MasterUsername: ${self:provider.environment.RDS_DB_MASTER_USER}
    MasterUserPassword: ${self:provider.environment.RDS_DB_MASTER_PWD}
    VPCSecurityGroups:
    - Fn::GetAtt: [ RDSSecurityGroup, GroupId ]
  DependsOn: RDSSecurityGroup
  DeletionPolicy: Snapshot