# RDS resources
RDSInstance:
  Type: AWS::RDS::DBInstance
  Properties:
    DBInstanceIdentifier: ${self:custom.projectPrefix}-RDS
    DBInstanceClass: db.t2.micro
    Engine: postgres
    EngineVersion: 10.4
    PubliclyAccessible: false
    AllocatedStorage: 20
    DBName: ${self:provider.environment.RDS_DB_NAME}
    MasterUsername: ${self:provider.environment.RDS_DB_MASTER_USER}
    MasterUserPassword: ${self:provider.environment.RDS_DB_MASTER_PWD}
  DeletionPolicy: Snapshot